{
    "name": "Fuze Restaurant Experience",
    "summary": "Branded storefront, native POS ordering, secure payments and kitchen display",
    "version": "19.0.2.0.3",
    "category": "Point of Sale",
    "author": "Spxcorp Limited",
    "website": "https://spxcorp.net",
    "license": "LGPL-3",
    "depends": [
        "website",
        "mail",
        "contacts",
        "point_of_sale",
        "pos_restaurant",
        "payment",
    ],
    "data": [
        "security/fuze_security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence.xml",
        "data/fuze_station_data.xml",
        "data/fuze_menu_products.xml",
        "data/ir_config_parameter.xml",
        "views/website_templates.xml",
        "views/kitchen_templates.xml",
        "views/fuze_kitchen_views.xml",
        "views/pos_config_views.xml",
        "views/product_views.xml",
        "views/pos_order_views.xml",
        "views/payment_templates.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "fuze_website/static/src/css/styles.css",
            "fuze_website/static/src/css/payment-branding.css",
        ],
    },
    "images": ["static/description/icon.png"],
    "application": True,
    "installable": True,
}
